### ISSUE TITLE
 Check failed: error == cudaSuccess (2 vs. 0)  out of memory.How to deal with it?

### ISSUE THREAD

**Issue by githubfeiwang** [szq0214/DSOD#11]

**Comment by wellingtonyl** [comment]
try to reduce the batchsize in DSOD300_pascal.py line 283

**Comment by moyans** [comment]
@githubfeiwang @szq0214 @wellingtonyl  My GPU type is GTX1080 ，only the Train batch_size:4 can run ，Is this normal?

**Comment by wellingtonyl** [comment]
normal, mine is M40, also batch_size=4

**Comment by moyans** [comment]
@wellingtonyl Thanks

**Comment by githubfeiwang** [comment]
Thanks !


________________________________
发件人: moyans <notifications@github.com>
发送时间: 2017年8月22日 8:04
收件人: szq0214/DSOD
抄送: githubfeiwang; Mention
主题: Re: [szq0214/DSOD] Check failed: error == cudaSuccess (2 vs. 0) out of memory.How to deal with it? (#11)


@githubfeiwang<https://github.com/githubfeiwang> @szq0214<https://github.com/szq0214> @wellingtonyl<https://github.com/wellingtonyl> My GPU type is GTX1080 ，only the Train batch_size:4 can run ，Is this normal?

―

**Comment by githubfeiwang** [comment]
Thanks !


________________________________
发件人: wellingtonyl <notifications@github.com>
发送时间: 2017年8月22日 7:07
收件人: szq0214/DSOD
抄送: githubfeiwang; State change
主题: Re: [szq0214/DSOD] Check failed: error == cudaSuccess (2 vs. 0) out of memory.How to deal with it? (#11)


try to reduce the batchsize in DSOD300_pascal.py line 283

―
