### ISSUE TITLE
I find the DSOD300_pascal.py can't breakpoint，When I stop running, it can not find the latest snapshoot

### ISSUE THREAD

**Issue by moyans** [szq0214/DSOD#15]
@szq0214 @liuzhuang13

**Comment by szq0214** [comment]
Hi @moyans, thanks for pointing out this, I will include an option to allow users to train DSOD from most recently saved snapshot soon.

**Comment by moyans** [comment]
@szq0214 Ok， Thanks

**Comment by szq0214** [comment]
@moyans  simply set "resume_training = True" (line 24) and uncomment line 498 in file "DSOD300_pascal.py" to retrain from most recent snapshot.

**Comment by moyans** [comment]
@szq0214 I get ,thank you for your reply
