### ISSUE TITLE
About the test GPU memory？

### ISSUE THREAD

**Issue by moyans** [szq0214/DSOD#16]
@szq0214 @liuzhuang13  When I'm trying test the video，the DSOD300 Occupy GPU memory is 1500M ，just like SSD_300_ResNet101 . I have tried the official optimized version of the[ densenet.](https://github.com/Tongcheng/DN_CaffeScript)，GPU memory footprint is not particularly serious，Is this a problem with version optimization?

**Comment by liuzhuang13** [comment]
Hi @moyans For convenience, we didn't use the official optimized version of densenet in the DSOD project. We just use the naive implementation.

**Comment by moyans** [comment]
@liuzhuang13  Thank you for your answer and look forward to your update - 。-

**Comment by moyans** [comment]
@liuzhuang13 Best wishes!
