### ISSUE TITLE
How to measure the inference time?

### ISSUE THREAD

**Issue by youngwanLEE** [szq0214/DSOD#17]
Hi,

I want to know how to measure the inference time? 

Did you use caffe time operator ? or Did you measure full time when VOC 4952 test images are tested ?

Thanks in advance :)

**Comment by szq0214** [comment]
Hi @youngwanLEE, We used a loop (more than 5000 times) and measured the mean time of the loop as the inference time of DSOD, we didn't use the caffe time operator.

**Comment by youngwanLEE** [comment]
Hi, @szq0214  thanks for your reply.

I couldn't fully figure out your demonstration.

What kind of loop ? such as detection forward pass time? 

SSD's original author commented he used total inference time when score_pascal.py program ended.

I want to measure the inference time by your same way. 

Could you explain your concrete way? 

Thanks :)

**Comment by szq0214** [comment]
Hi @youngwanLEE, 
Our loop only measured the whole forward pass time without the data preprocessing (e.g., resize inputs). Inference time may be slightly off the SSD's value but not much.
