### ISSUE TITLE
cannot agree faster-rcnn cannot converge when training from scratch

### ISSUE THREAD

**Issue by argman** [szq0214/DSOD#2]
Or do you mean when training from scratch , performance is much worse than fine-tuning ?

And tks for sharing the code.

**Comment by szq0214** [comment]
@argman We tried py-faster-rcnn and py-R-FCN to train detectors from scratch with VGGNet/ResNet/DenseNet backbone networks on pascal voc dataset. Unfortunately, these models could not converge successfully and obtained very poor generalization performance (~15%mAP).
