### ISSUE TITLE
The training time

### ISSUE THREAD

**Issue by Dido0o0** [szq0214/DSOD#22]
How long is your training time based on one TitanX GPU or 8 GPUs?

**Comment by szq0214** [comment]
Hi @Dido0o0, it depends on the number and the type of your GPUs. If you only have one, I think it will take a very long time.

**Comment by achalddave** [comment]
Do you have an estimate of number of hours / days / weeks it takes to train the models? Any number would be helpful - say, DSOD300 on PASCAL VOC 2007 trainval+2012 trainval, on whatever set up you used? Right now it looks like it will take me ~7-10 days to train on a 4 GPU 1080ti machine, so I'm not sure if I'm doing something wrong.
