### ISSUE TITLE
the last pooling size mismatch

### ISSUE THREAD

**Issue by zhangkaij** [szq0214/DSOD#23]
the last pooling size is not inconsistent with paper.
in the paper:
the size of the pooling7 feature map = 1\*1
in model_libs.py:
the size of the pooling7 feature map = 2\*2

Also, DSOD prediction layers differ from the figure 1 in paper.

**Comment by szq0214** [comment]
Hi @zhangkaij, thanks for pointing out this! I will correct it in our revision.
