### ISSUE TITLE
How to prepare voc12 test lmdb

### ISSUE THREAD

**Issue by lzx1413** [szq0214/DSOD#24]
I want to know how to prepare voc12 test lmdb to run training on the voc07++12 dataset. Anyone can help me? thanks a lot.

**Comment by ujsyehao** [comment]
@lzx1413 Do you know how to do?

**Comment by ujsyehao** [comment]
@lzx1413 I read it, but it just creates VOC0712Plus_trainval_lmdb, and not creates voc2012_test_lmdb, how to test?
