### ISSUE TITLE
about how to batch test many image files？

### ISSUE THREAD

**Issue by hu5tao** [szq0214/DSOD#27]
I copy to my all test files to a path , and i want to batch test this image files,and to get the annotations of test images files ?Could you tell me a method？

**Comment by szq0214** [comment]
Hi @hu5tao, 

I'm sorry that testing in a batch is not supported by the current demo script. Maybe I can add this feature in the near future if I have time. 

Another solution is to generate the LMDB file for your own test images. The LMDB file should have the same format as the voc test dataset. And then you can use "score_DSOD300_pascal.py" script to test with a batch images.
