### ISSUE TITLE
No such File or Directory - Core Dumped

### ISSUE THREAD

**Issue by zeehasham** [szq0214/DSOD#32]
I am getting the following message when running train command

python examples/dsod/DSOD300_pascal.py

I0312 18:13:06.186707 31109 layer_factory.hpp:77] Creating layer data
I0312 18:13:06.186813 31109 net.cpp:100] Creating Layer data
I0312 18:13:06.186830 31109 net.cpp:408] data -> data
I0312 18:13:06.186846 31109 net.cpp:408] data -> label
F0312 18:13:06.189031 31210 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7f8d26f785cd  google::LogMessage::Fail()
    @     0x7f8d26f7a433  google::LogMessage::SendToLog()
    @     0x7f8d26f7815b  google::LogMessage::Flush()
    @     0x7f8d26f7ae1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8d2784b770  caffe::db::LMDB::Open()
    @     0x7f8d2768a396  caffe::DataReader<>::Body::InternalThreadEntry()
    @     0x7f8d2767c465  caffe::InternalThread::entry()
    @     0x7f8d1cc4f5d5  (unknown)
    @     0x7f8d159ee6ba  start_thread
    @     0x7f8d25fcf3dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)

Any help would be appreciated. All steps before running the training command were successful.

**Comment by szq0214** [comment]
Hi @zeehasham, I guess this is because you didn't replace the lmdb links with yours (line 29 and line 31 in DSOD300_pascal.py). I will share our lmdb files (voc 07+12, voc07++12, voc12 and coco) soon.
