### ISSUE TITLE
Reproduced result is lower than the reported result

### ISSUE THREAD

**Issue by youngwanLEE** [szq0214/DSOD#39]
Hi, 

I tried to train DSOD300 using [this file](https://github.com/szq0214/DSOD/blob/master/DSOD300_pascal.py) on 8 TITAN Xp GPU.

But the result is 76.94% which is lower than the reported result(77.7%).

I couldn't find out why this problem occurs. 

Could anyone face this problem?

![image](https://user-images.githubusercontent.com/13238578/50752647-501b4380-1292-11e9-972b-72aa0f88ea47.png)

**Comment by szq0214** [comment]
Hi @youngwanLEE, the result may be slightly fluctuant under different training. You can search for a better one around it in the log file.
