### ISSUE TITLE
Why the speed of DSOD is too slow in the process of training?

### ISSUE THREAD

**Issue by defei-coder** [szq0214/DSOD#43]
@szq0214 
Hi!
I trained the DSOD by using my datasets,but time is 10 times the time of the SSD.
Why DSOD is so slow?

**Comment by szq0214** [comment]
Hi @Mrxiaofei, the main reason is that the batch size we used in DSOD is much larger than SSD. I think you can reduce the total #iterations to some extent to speed up training, or reduce #batchsize but include some new techniques like Group Norm or Sync BN. Also, VGG backbone in SSD is faster than the model we used in DSOD.
