### ISSUE TITLE
Couldn't find any detections

### ISSUE THREAD

**Issue by miraclewkf** [szq0214/DSOD#7]
When I run` python DSOD300_pascal.py`, I get many information like: I0809 19:00:06.018213  8332 detection_output_layer.cu:113] Couldn't find any detections.
What should I do?

**Comment by szq0214** [comment]
Hi @miraclewkf, see https://github.com/BVLC/caffe/issues/4594. I think it's an SSD bug and has already been fixed. I recommend you to use the latest version of SSD (https://github.com/weiliu89/caffe/tree/ssd).

**Comment by shudct** [comment]
Hi, @miraclewkf , I meet the same questions as you. And I have already used the latest version of SSD. Have you solved the problem? thank you

**Comment by Tmono** [comment]
I meet the same questions...And I change the batch size to a small one, it didn't work.

**Comment by moyans** [comment]
My detection_eval only 0.045 in 3.1w Iteration， But the loss is normal

**Comment by szq0214** [comment]
@moyans, Please use our default parameters setting. If you only have one GPU device, just change "batch_size" to 4 with other parameters constant. I guess this is because your "accum_batch_size" is set to a very small value.

**Comment by moyans** [comment]
Thank to @szq0214 , I change the "accum_batch_size" like to "batch_size" , I set to 128 now，But it is really slow speed。

**Comment by edwwang** [comment]
@miraclewkf @shudct Hi, have you solved this problem? I have already used the lattest ssd version and tried to modify the batch_size to 4 and 16 , but the question  remains the same . Btw, my machine has got 4 GPUs , and I have changed the contents in examples/dsod/DSOD300_pascal.py from ' gpus = "0,1,2,3,4,5,6,7" ' to ' gpus = "0,1,2,3" '.

**Comment by shudct** [comment]
@edwwang The information 'Couldn't find any detections' is just a warning which means in this image there is no object detected. DSOD trains from scratch so it's very possible to detect no objects for the first test. And I ignore the warning, there is no that for the next test.

**Comment by edwwang** [comment]
@shudct Ok i know. Thanks for your answer.

**Comment by BestSongEver** [comment]
@moyans 
Hi,I'm facing the same problem  with u, achiving a detection_eval = 0.0555858. Have u solve the problem?  And how?
Please help
Thx a lot : ).

**Comment by moyans** [comment]
@BestSongEver when I set ‘accum_batch_size’ to 128（before I set it was equal to "batch_size: 4"  ），the detection_eval become normal.

**Comment by lzx1413** [comment]
https://github.com/szq0214/DSOD/blob/2d33da5ca65dfa31d3bf8e701fa9e4e0a6a804df/DSOD300_pascal.py#L334
turn this  False and everything will be OK.
