### ISSUE TITLE
will release the trianing code?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [szq0214/DSOD#8]
hi @szq0214,
will you release the training code?

thanks.

**Comment by szq0214** [comment]
Hi @zimenglan-sysu-512, DSOD300_xxx.py is the script for training. Please see our README.md for details. :)

**Comment by zimenglan-sysu-512** [comment]
hi @szq0214,

Thanks for reminding me.
Btw, do you try `focal loss` to boost the performance?

Thanks.

**Comment by liuzhuang13** [comment]
@zimenglan-sysu-512  We didn't try that, but that might be an interesting idea. Thanks
